-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 05:56:18 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema adlive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adlive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adlive` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `adlive` ;

-- -----------------------------------------------------
-- Table `adlive`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adlive`.`channel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adlive`.`channel_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adlive`.`channel_url` (
  `channel_id` INT UNSIGNED NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB
COMMENT = '配信URL';


-- -----------------------------------------------------
-- Table `adlive`.`stream_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adlive`.`stream_url` (
  `channel_id` INT UNSIGNED NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  INDEX `fk_channel_id_idx` (`channel_id` ASC),
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB
COMMENT = 'ライブ動画を受け取るURL';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
